/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function validateConfig(configStr: string): void
export function validatePackage(appPath: string, nodeModulesPath: string, cliVersion: string): void
