/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function validateConfig(configStr: string): boolean
export function validatePackage(appPath: string, nodeModulesPath: string): boolean
export function validateEnv(): boolean
export function validateRecommend(appPath: string): boolean
