/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function validateConfig(configStr: string): void
export function validatePackage(appPath: string, nodeModulesPath: string): void
export function validateEnv(): void
export function validateRecommend(appPath: string): void
export function validateEslint(): void
