/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum MessageKind {
  Info = 0,
  Error = 1,
  Success = 2,
  Warning = 3,
  Manual = 4
}
export interface Message {
  kind: MessageKind
  content: string
  solution?: string
}
export interface ValidateResult {
  isValid: boolean
  messages: Array<Message>
}
export function validateConfig(configStr: string, remoteSchemaUrl: string, useRemoteSchema: boolean): Promise<ValidateResult>
export function validateConfigPrint(configStr: string, remoteSchemaUrl: string, useRemoteSchema: boolean): Promise<boolean>
export function validatePackage(appPath: string, nodeModulesPath: string): ValidateResult
export function validatePackagePrint(appPath: string, nodeModulesPath: string): boolean
export function validateEnv(): ValidateResult
export function validateEnvPrint(): boolean
export function validateRecommend(appPath: string): ValidateResult
export function validateRecommendPrint(appPath: string): boolean
